var data = [{
    'state':'AK',
    'region':'PACIFIC',
    'location':[1,7]
},
    {
        'state':'HI',
        'region':'PACIFIC',
        'location':[1,2]
    },
    {
        'state':'WA',
        'region':'WEST',
        'location':[2,6]
    },
    {
        'state':'OR',
        'region':'WEST',
        'location':[2,5]
    },
    {
        'state':'CA',
        'region':'WEST',
        'location':[2,4]
    },
    {
        'state':'ID',
        'region':'WEST',
        'location':[3,6]
    },
    {
        'state':'UT',
        'region':'WEST',
        'location':[3,5]
    },
    {
        'state':'NV',
        'region':'WEST',
        'location':[3,4]
    },
    {
        'state':'AZ',
        'region':'WEST',
        'location':[3,3]
    },
    {
        'state':'MT',
        'region':'WEST',
        'location':[4,6]
    },
    {
        'state':'WY',
        'region':'WEST',
        'location':[4,5]
    },
    {
        'state':'CO',
        'region':'WEST',
        'location':[4,4]
    },
    {
        'state':'NM',
        'region':'WEST',
        'location':[4,3]
    },
    {
        'state':'ND',
        'region':'MIDWEST',
        'location':[5,6]
    },
    {
        'state':'SD',
        'region':'MIDWEST',
        'location':[5,5]
    },
    {
        'state':'NE',
        'region':'MIDWEST',
        'location':[5,4]
    },
    {
        'state':'KS',
        'region':'MIDWEST',
        'location':[5,3]
    },
    {
        'state':'OK',
        'region':'SOUTH',
        'location':[5,2]
    },
    {
        'state':'TX',
        'region':'SOUTH',
        'location':[5,1]
    },
    {
        'state':'MN',
        'region':'MIDWEST',
        'location':[6,6]
    },
    {
        'state':'IA',
        'region':'MIDWEST',
        'location':[6,5]
    },
    {
        'state':'MO',
        'region':'MIDWEST',
        'location':[6,4]
    },
    {
        'state':'AR',
        'region':'SOUTH',
        'location':[6,3]
    },
    {
        'state':'LA',
        'region':'SOUTH',
        'location':[6,2]
    },
    {
        'state':'WI',
        'region':'MIDWEST',
        'location':[7,6]
    },
    {
        'state':'IL',
        'region':'MIDWEST',
        'location':[7,5]
    },
    {
        'state':'IN',
        'region':'MIDWEST',
        'location':[7,4]
    },
    {
        'state':'KY',
        'region':'SOUTH',
        'location':[7,3]
    },
    {
        'state':'MS',
        'region':'SOUTH',
        'location':[7,2]
    },
    {
        'state':'MI',
        'region':'MIDWEST',
        'location':[8,6]
    },
    {
        'state':'OH',
        'region':'MIDWEST',
        'location':[8,5]
    },
    {
        'state':'WV',
        'region':'SOUTH',
        'location':[8,4]
    },
    {
        'state':'TN',
        'region':'SOUTH',
        'location':[8,3]
    },
    {
        'state':'AL',
        'region':'SOUTH',
        'location':[8,2]
    },
    {
        'state':'PA',
        'region':'NORTHEAST',
        'location':[9,5]
    },
    {
        'state':'VA',
        'region':'SOUTH',
        'location':[9,4]
    },
    {
        'state':'SC',
        'region':'SOUTH',
        'location':[9,3]
    },
    {
        'state':'GA',
        'region':'SOUTH',
        'location':[9,2]
    },
    {
        'state':'NY',
        'region':'NORTHEAST',
        'location':[10,6]
    },
    {
        'state':'NJ',
        'region':'NORTHEAST',
        'location':[10,5]
    },
    {
        'state':'MD',
        'region':'SOUTH',
        'location':[10,4]
    },
    {
        'state':'NC',
        'region':'SOUTH',
        'location':[10,3]
    },
    {
        'state':'FL',
        'region':'SOUTH',
        'location':[10,1]
    },
    {
        'state':'VT',
        'region':'NORTHEAST',
        'location':[11,7]
    },
    {
        'state':'MA',
        'region':'NORTHEAST',
        'location':[11,6]
    },
    {
        'state':'CT',
        'region':'NORTHEAST',
        'location':[11,5]
    },
    {
        'state':'DE',
        'region':'SOUTH',
        'location':[11,4]
    },
    {
        'state':'ME',
        'region':'NORTHEAST',
        'location':[12,8]
    },
    {
        'state':'NH',
        'region':'NORTHEAST',
        'location':[12,7]
    },
    {
        'state':'RI',
        'region':'NORTHEAST',
        'location':[12,6]
    }
];
// Will be used to the save the loaded JSON data
var allData = [];
loadData();

function loadData() {
    d3.json("data/processed_data/factors.json", function(error, jsonData){
        if(!error){
            allData = jsonData;

            createVis();
        }
    });
}

function createVis() {

    // Instantiate visualization objects here

    cartogramChart = new CartogramChart("cartoGram", allData);
}

